import type { Metadata } from "next";
import { Bowlby_One_SC, DM_Mono } from "next/font/google";
import "./globals.css";
import { NavBar } from "@/components/NavBar";
import { SVGFilters } from "@/components/SVGFilters";
import { Footer } from "@/components/Footer";
import { SkateboardProvider } from "@/contexts/SkateboardContext";

const bowlby = Bowlby_One_SC({
  variable: "--font-bowlby-sc",
  subsets: ["latin"],
  weight: ["400"],
});

const DMMono = DM_Mono({
  variable: "--font-DM-mono",
  subsets: ["latin"],
  weight: ["500"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/icon.svg",
    shortcut: "/icon.svg",
    apple: "/icon.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/icon.svg" type="image/svg+xml" />
        <link rel="shortcut icon" href="/icon.svg" type="image/svg+xml" />
      </head>
      <body
        className={`${bowlby.variable} ${DMMono.variable} antialiased font-medium text-zinc-800
        `}
      >
        <SkateboardProvider>
          <main>
            <NavBar />
            {children}
            <Footer />
          </main>
          <SVGFilters />
        </SkateboardProvider>
      </body>
    </html>
  );
}
